[env:m5stack-atom]
platform = espressif32@6.3.2
board = m5stack-atom
framework = arduino
upload_speed = 1500000
monitor_speed = 115200
build_flags =
    -DCORE_DEBUG_LEVEL=5
lib_deps =
   ; M5Unified=https://github.com/m5stack/M5Unified
    M5Atom=https://github.com/m5stack/M5Atom
    FastLED=https://github.com/FastLED/FastLED